name: TopBalance
version: ${project.version}
main: xyz.efekurbann.topbalance.TopBalancePlugin
api-version: 1.12
depend: [ Vault, SkCore ]
authors: [ hyperion, Highest ]
commands:
  baltop:
    aliases:
      - topbalance
      - balancetop
      - baltop